### ISSUE TITLE
Trimmed last character when sending message

### ISSUE THREAD

**Issue by cinorid** [PrivacyForge/ChatGuard#10]
![Screenshot_2024-03-08-21-37-01-387_com.kiwibrowser.browser-edit.jpg](https://github.com/PrivacyForge/ChatGuard/assets/10947730/4bf9e23d-f7d2-4234-8950-519afb37753b)

**Comment by mostafa-kheibary** [comment]
https://github.com/PrivacyForge/ChatGuard/releases/tag/v0.9.1-beta

In the latest version that we published this issue had been fixed
if the issue still remain on the version 0.9.1, please let us know

**Comment by cinorid** [comment]
I can confirm that this bug has been fixed
