### ISSUE TITLE
Request button on android not working

### ISSUE THREAD

**Issue by cinorid** [PrivacyForge/ChatGuard#2]
I'm using Kiwi Browser to use this extension on Android.
after pressing the handshake request button it navigates to the payment request page and no handshake message has been sent.
| Screenshot 1                            | Screenshot 2                            | Screenshot 3                                     |
| ----------------------------------- | ----------------------------------- | ------------------------------------------- |
| ![Screenshot_com kiwibrowser browser_1](https://github.com/mostafa-kheibary/ChatGuard/assets/10947730/593a65f8-3ffb-4761-8a1b-a4d4804ea0bd) | ![Screenshot_com kiwibrowser browser_2 jpg](https://github.com/mostafa-kheibary/ChatGuard/assets/10947730/f36e4f7c-0102-40cf-be93-c0fc36b79e54) | ![Screenshot_com kiwibrowser browser_3](https://github.com/mostafa-kheibary/ChatGuard/assets/10947730/dbcf3a8f-6ba0-462e-88f6-40791aa9bbe3) |

**Comment by mostafa-kheibary** [comment]
are you using 0.5.0 version of chatguard ?
https://github.com/mostafa-kheibary/ChatGuard/releases/tag/v0.5.0-beta

**Comment by cinorid** [comment]
> are you using 0.5.0 version of chatguard ? https://github.com/mostafa-kheibary/ChatGuard/releases/tag/v0.5.0-beta

yes

**Comment by mostafa-kheibary** [comment]
thank you for the report.
i will fix it and inform you about the update in this thread.

**Comment by cinorid** [comment]
Thanks

**Comment by mostafa-kheibary** [comment]
It has been fixed; please notify me if the problem still exists.
Otherwise, close the issue. Thank you for the feedback :)

https://github.com/mostafa-kheibary/ChatGuard/releases/tag/v0.5.2-beta

**Comment by cinorid** [comment]
The problem has been fixed 👍🏼
