### ISSUE TITLE
Message corruption on very long messages

### ISSUE THREAD

**Issue by cinorid** [PrivacyForge/ChatGuard#3]
If the message is very long, it will be split by the web client and the extension cannot decrypt it.

**Comment by mostafa-kheibary** [comment]
Yes, I am currently facing a problem.
I have a solution for it, which involves splitting a message at a certain length by the extension and sending it in multiple messages as chunks with a numbered order indicating the sequence of each chunk. 
and the extention have local Queue to store and remember the chunks

I have already implemented part of this solution, but it needs some fixes and there is lots of limitation that the clients gives us. I'll work on resolving the issues and plan to release the updated version soon.

**Comment by mostafa-kheibary** [comment]
https://github.com/PrivacyForge/ChatGuard/releases/tag/v0.9.1-beta

We limit the message length to be bellow 1200 character on version 0.9.1
