### ISSUE TITLE
Add encrypted message indicator

### ISSUE THREAD

**Issue by cinorid** [PrivacyForge/ChatGuard#9]
It would be great if the messages sent or received in encrypted form were distinguishable from regular messages.

**Comment by mostafa-kheibary** [comment]
I'm actively working on it, and I'm optimistic it will be included in the 0.7.0 version.
Thanks for the feedback!

**Comment by mostafa-kheibary** [comment]
https://github.com/PrivacyForge/ChatGuard/releases/tag/v0.7.0-beta

i added a basic indicator emoji (🔒) to indicate the encrypted message with non encrypted message
